### ISSUE TITLE
Memory exhaustion for large request.

### ISSUE THREAD

**Issue by defnull** [etianen/aiohttp-wsgi#7]
The WSGI adapter reads the complete request body into memory. This results in extreme memory consumption for large file uploads and makes it very easy to run denial-of-service attacks.

    curl --data-binary "@/dev/zero" http://example.com/wsgi

**Comment by etianen** [comment]
We have to buffer the entire request in order to prevent slow network
clients from stalling the wsgi worker threads. However, the current
situation is not ideal.

I think it needs to be possible to configure a max request size for the
wsgi handler, which will reject an incoming request with the appropriate
status code if it's above the allowed size. Setting it to a default value
of 100MB or so would seem to mitigate malicious attacks while still
allowing most sensible files through.

Sound reasonable?

**Comment by defnull** [comment]
Then you could still get the server into swapping with multiple smaller requests. Also, uploading bigger files would no longer be possible. Why not buffer into a reasonably sized `tempfile.SpooledTemporaryFile`, chunk by chunk?

Other than that, stalling the worker thread pool is still better than exhausting the server memory. It brings down only the WSGI application, not the whole server.

**Comment by etianen** [comment]
A spoiled temporary file seems good too, but I think a max upload size is
still sensible. Most webservers have this built in. Nginx limits to 5MB by
default, I think, which is tiny!

**Comment by etianen** [comment]
Here we go: https://github.com/etianen/aiohttp-wsgi/blob/master/CHANGELOG.rst#040
